import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import HeaderPage from "@/components/Header";
import Navbar from "@/components/Navbar";

import { Suspense } from 'react'
import Marquee from "@/components/Marquee";

const notoSerifBengali = Noto_Serif_Bengali({
  subsets: ["latin", "bengali"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${notoSerifBengali.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <HeaderPage></HeaderPage>
        <Suspense fallback={<p>Loading categories...</p>}>
          <Navbar />
        </Suspense>
        <Suspense fallback={<p>Loading Headlines...</p>}>
        <Marquee></Marquee>
        </Suspense>
        
        <main className="bg-[#F0F5F0]">{children}</main>
      </body>
    </html>
  );
}
